// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByEb2uoz7PAZXiiNPWBN8T7fnDwhTftdc',
    appId: '1:611622878418:web:3a18485eae1dba1345810b',
    messagingSenderId: '611622878418',
    projectId: 'news-app-a302c',
    authDomain: 'news-app-a302c.firebaseapp.com',
    storageBucket: 'news-app-a302c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3gvLHpaahiv9qeUTC98uDfr8SBGiOC0g',
    appId: '1:611622878418:android:13471e988a478f3845810b',
    messagingSenderId: '611622878418',
    projectId: 'news-app-a302c',
    storageBucket: 'news-app-a302c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl7742iEtMjkycQacUVUCd030AEQEl7gM',
    appId: '1:611622878418:ios:1cfa25b724aabf4c45810b',
    messagingSenderId: '611622878418',
    projectId: 'news-app-a302c',
    storageBucket: 'news-app-a302c.appspot.com',
    iosBundleId: 'com.example.newsAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl7742iEtMjkycQacUVUCd030AEQEl7gM',
    appId: '1:611622878418:ios:1cfa25b724aabf4c45810b',
    messagingSenderId: '611622878418',
    projectId: 'news-app-a302c',
    storageBucket: 'news-app-a302c.appspot.com',
    iosBundleId: 'com.example.newsAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByEb2uoz7PAZXiiNPWBN8T7fnDwhTftdc',
    appId: '1:611622878418:web:29218f6e2cc62a2845810b',
    messagingSenderId: '611622878418',
    projectId: 'news-app-a302c',
    authDomain: 'news-app-a302c.firebaseapp.com',
    storageBucket: 'news-app-a302c.appspot.com',
  );
}
